include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    literal_only_boolean_expressions: false
    require_trailing_commas: false
    comment_references: false
    only_throw_errors: false
    unnecessary_library_directive: false
    avoid_positional_boolean_parameters: false
#    avoid_dynamic_calls: false
#    use_build_context_synchronously: false
