name: flutter_helper_utils
description: The Flutter Helper Utils Package offers various extensions and helper methods that can make development more efficient.
repository: https://github.com/omar-hanafy/flutter_helper_utils
version: 3.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0"
  mime: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
