name: flutter_helper_utils
description: The Flutter Helper Utils Package offers various extensions and helper methods that can make development more efficient.
repository: https://github.com/omar-hanafy/flutter_helper_utils
version: 8.0.0-dev.1
topics:
  - utilities
  - helpers
  - extensions
  - productivity
  - adaptive

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.29.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_helper_utils: ^5.0.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
