name: flutter_helper_utils
description: The Flutter Helper Utils Package offers various extensions and helper methods that can make development more efficient.
repository: https://github.com/omar-hanafy/flutter_helper_utils
version: 9.0.0
topics:
  - utilities
  - helpers
  - extensions
  - productivity
  - adaptive

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: ">=3.41.0"

dependencies:
  dart_helper_utils: ">=6.0.0 <7.0.0"
  flutter:
    sdk: flutter
  intl: ">=0.20.0 <1.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
