name: flutter_helper_utils
description: The Flutter Helper Utils Package offers various extensions and helper methods that can make development more efficient.
repository: https://github.com/omar-hanafy/flutter_helper_utils
version: 6.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_helper_utils: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
